const state={operation:'mixed',difficulty:'medium',count:20,index:0,score:0,questions:[],mistakes:[],startedAt:0,timerId:null,elapsed:0};
const $=s=>document.querySelector(s);const setup=$('#setupPanel'),quiz=$('#quizPanel'),result=$('#resultPanel');
const clientKey='little-mental-math-client-id';
document.querySelectorAll('.choice').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.choice').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');state.operation=btn.dataset.operation}));
function rand(min,max){return Math.floor(Math.random()*(max-min+1))+min}
function makeQuestion(){const max={easy:20,medium:100,hard:1000}[state.difficulty];let op=state.operation==='mixed'?['add','subtract','multiply','divide'][rand(0,3)]:state.operation;let a,b,answer,symbol;if(op==='add'){a=rand(1,max);b=rand(1,max-a);answer=a+b;symbol='＋'}else if(op==='subtract'){a=rand(2,max);b=rand(1,a);answer=a-b;symbol='−'}else if(op==='multiply'){const factorMax=state.difficulty==='hard'?30:state.difficulty==='medium'?12:10;a=rand(1,factorMax);b=rand(1,factorMax);answer=a*b;symbol='×'}else{b=rand(1,state.difficulty==='hard'?20:10);answer=rand(1,state.difficulty==='hard'?50:10);a=b*answer;symbol='÷'}return{a,b,answer,symbol,text:`${a} ${symbol} ${b} = ?`}}
function formatTime(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function localDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function deviceId(){let id=localStorage.getItem(clientKey);if(!id){id=crypto.randomUUID();localStorage.setItem(clientKey,id)}return id}
function formatDay(date){const [,month,day]=date.split('-');return `${Number(month)} 月 ${Number(day)} 日`}
function updateHistory(days=[]){const today=days.find(day=>day.date===localDate());const recent=days.slice(0,7);const weekTotal=recent.reduce((sum,day)=>sum+day.total,0);$('#todaySummary').textContent=today?`${today.total} 题`:'还未练习';$('#weekSummary').textContent=weekTotal?`${weekTotal} 题`:'0 题';$('#todayCount').textContent=today?today.total:0;$('#historyList').innerHTML=days.length?recent.map(day=>{const rate=Math.round(day.correct/day.total*100);return `<div class="history-day"><span class="history-date">${formatDay(day.date)}</span><span class="history-detail">${day.total} 题 · ${formatTime(day.elapsed)} · 错 ${day.mistakes} 题</span><strong class="history-rate ${rate<70?'needs-practice':''}">${rate}%</strong></div>`}).join(''):'<p class="history-empty">完成第一组练习后，这里会留下每天的学习足迹。</p>'}
async function loadHistory(){try{const response=await fetch(`/api/history?clientId=${encodeURIComponent(deviceId())}`);if(!response.ok)throw new Error('history unavailable');const data=await response.json();updateHistory(data.days||[])}catch{$('#todaySummary').textContent='暂未同步';$('#weekSummary').textContent='—';$('#historyList').innerHTML='<p class="history-empty">学习档案正在准备中，稍后再试即可。</p>'}}
async function saveSession(){try{await fetch('/api/history',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({clientId:deviceId(),date:localDate(),total:state.count,correct:state.score,elapsed:state.elapsed,mistakes:state.mistakes.length})});await loadHistory()}catch{}}
function start(){state.difficulty=$('#difficulty').value;state.count=Number($('#questionCount').value);state.index=0;state.score=0;state.mistakes=[];state.questions=Array.from({length:state.count},makeQuestion);state.startedAt=Date.now();state.elapsed=0;clearInterval(state.timerId);state.timerId=setInterval(()=>{$('#timer').textContent=formatTime(Math.floor((Date.now()-state.startedAt)/1000))},1000);setup.classList.add('hidden');result.classList.add('hidden');quiz.classList.remove('hidden');showQuestion()}
function showQuestion(){const q=state.questions[state.index];$('#progressText').textContent=`第 ${state.index+1} / ${state.count} 题`;$('#progressBar').style.width=`${state.index/state.count*100}%`;$('#questionText').textContent=q.text;$('#feedback').textContent='';$('#feedback').className='feedback';$('#answerInput').value='';$('#answerInput').focus()}
function submit(e){e.preventDefault();const input=$('#answerInput');if(input.value.trim()==='')return;const q=state.questions[state.index];const answer=Number(input.value);const feedback=$('#feedback');if(answer===q.answer){state.score++;feedback.textContent='回答正确！继续保持 ✦';feedback.classList.add('good')}else{feedback.textContent=`再想想，正确答案是 ${q.answer}`;feedback.classList.add('bad');state.mistakes.push({q,answer})}input.disabled=true;setTimeout(()=>{input.disabled=false;if(state.index<state.count-1){state.index++;showQuestion()}else finish()},700)}
function finish(){clearInterval(state.timerId);state.elapsed=Math.floor((Date.now()-state.startedAt)/1000);quiz.classList.add('hidden');result.classList.remove('hidden');const accuracy=Math.round(state.score/state.count*100);$('#scoreText').textContent=state.score;$('#totalText').textContent=state.count;$('#accuracyText').textContent=`${accuracy}%`;$('#timeText').textContent=formatTime(state.elapsed);$('#mistakeText').textContent=state.mistakes.length;$('#resultTitle').textContent=accuracy>=90?'太厉害了！':accuracy>=70?'做得不错！':'再练一组会更好！';$('#mistakeList').innerHTML=state.mistakes.map(({q,answer})=>`<div class="mistake-item"><span>${q.a} ${q.symbol} ${q.b} = ${answer}</span><span class="right">正确：${q.answer}</span></div>`).join('');saveSession()}
function goHome(){result.classList.add('hidden');quiz.classList.add('hidden');setup.classList.remove('hidden')}
$('#startButton').addEventListener('click',start);$('#answerForm').addEventListener('submit',submit);$('#quitButton').addEventListener('click',finish);$('#retryButton').addEventListener('click',start);$('#homeButton').addEventListener('click',goHome);loadHistory();
